# Description
# ===========
# Use this playbook to query all the resources in a given resource group.
# This sample requires Ansible 2.6 

---
- hosts: localhost
  vars:
    resource_group: zims-openshift-2
    location: eastus
    vm_name: mycluster-master-0

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: openshiftvnet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: openshiftvnet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: mycluster_publicip

    - name: Create infrastructure NSG
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: mycluster-infra-nsg
        rules:
          - name: allowSSHin_all
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound
          - name: allowHTTPSIn_all
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 200
            direction: Inbound
          - name: allowHTTPIn_all
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 300
            direction: Inbound

    - name: Create master NSG
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: mycluster-master-nsg
        rules:
          - name: allowSSHin_all
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound
          - name: allowHTTPSIn_all
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 200
            direction: Inbound

    - name: Create node NSG
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: mycluster-node-nsg
        rules:
          - name: allowSSHin_all
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound
          - name: allowHTTPSIn_all
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 200
            direction: Inbound
          - name: allowHTTPIn_all
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 300
            direction: Inbound

    - name: Create virtual network inteface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: mycluster-master-0-nic
        virtual_network: openshiftvnet
        subnet: "{{ vm_name }}"
        #public_ip_name: "{{ vm_name }}"
        security_group: mycluster-master-nsg

    - name: Create virtual network inteface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: mycluster-node-0-nic
        virtual_network: openshiftvnet
        subnet: "{{ vm_name }}"
        #public_ip_name: "{{ vm_name }}"
        security_group: mycluster-node-nsg


    - name: Create master VMs
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: mycluster-master-0
        managed_disk_type: Standard_LRS
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        admin_password: Password@123
        network_interfaces: mycluster-master-0-nic
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: 7.4
          version: latest
        data_disks:
            - lun: 0
              disk_size_gb: 64
              managed_disk_type: Standard_LRS

    - name: Create node VMs
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: mycluster-node-0
        managed_disk_type: Standard_LRS
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        admin_password: Password@123
        network_interfaces: mycluster-node-0-nic
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: 7.4
          version: latest
        data_disks:
            - lun: 0
              disk_size_gb: 64
              managed_disk_type: Standard_LRS


    - name: Create master availability set
      azure_rm_availabilityset:
        name: masteravailabilityset
        location: eastus
        resource_group: "{{ resource_group }}"

    - name: Create node availability set
      azure_rm_availabilityset:
        name: nodeavailabilityset
        location: eastus
        resource_group: "{{ resource_group }}"

    - name: Create a load balancer
      azure_rm_loadbalancer:
        name: mycluster-masterlb
        location: eastus
        resource_group: "{{ resource_group }}"
        public_ip: mycluster_publicip
        probe_protocol: Tcp
        probe_port: 80
        probe_interval: 10
        probe_fail_count: 3
        protocol: Tcp
        load_distribution: Default
        frontend_port: 80
        backend_port: 8080
        idle_timeout: 4
        natpool_frontend_port_start: 1030
        natpool_frontend_port_end: 1040
        natpool_backend_port: 80
        natpool_protocol: Tcp

